#global cors:
#  add-to-simple-url-handler-mapping: true
#  corsConfigurations:
#    '[/**]':
#      allowedOrigins:
#        - "http://localhost:3000"
#      allowedMethods:
#        - GET
#        - POST
#        - PUT
#        - DELETE
#        - OPTIONS
#      allowedHeaders:
#        - "*"
#      allowCredentials: true